name: ":windows: Build"

on:
  workflow_call:  # Makes this workflow reusable 

jobs:
  build:
    name: ":windows: Build"
    runs-on: windows-latest-8-cores
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./...
        env:
          CGO_ENABLED: "1"  # Enable CGO for native builds 