name: Build

on:
  workflow_call:  # Makes this workflow reusable 

jobs:
  build:
    timeout-minutes: 5  # Add timeout of 5 minutes
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./...
        env:
          CGO_ENABLED: "1"  # Enable CGO for native builds 