on:
  workflow_call:  # Makes this workflow reusable

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - id: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - id: go-build
        run: go build -o flyssh-darwin-amd64 ./cmd/flyssh
        env:
          CGO_ENABLED: "0"  # Disable CGO for static builds
          
      - id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: flyssh-macos
          path: flyssh-darwin-amd64
          retention-days: 1 