name: Check Changes

on:
  workflow_call:
    outputs:
      has_substantial_changes:
        description: "Whether substantial changes were found"
        value: ${{ jobs.check.outputs.has_substantial_changes }}
      release_notes:
        description: "Generated release notes"
        value: ${{ jobs.check.outputs.release_notes }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has_substantial_changes: ${{ steps.verify-changes.outputs.has_substantial_changes }}
      release_notes: ${{ steps.verify-changes.outputs.release_notes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Verify Changes
        id: verify-changes
        run: |
          ./scripts/check-changes ${{ github.event.before }}
          {
            echo "release_notes<<EOF"
            cat release_notes.txt
            echo "EOF"
          } >> $GITHUB_OUTPUT 