name: Check Changes

on:
  workflow_call:
    outputs:
      has_substantial_changes:
        description: "Whether substantial changes were found"
        value: ${{ jobs.check.outputs.has_substantial_changes }}
      release_notes:
        description: "Generated release notes"
        value: ${{ jobs.check.outputs.release_notes }}
    secrets:
      ANTHROPIC_API_KEY:
        required: false

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has_substantial_changes: ${{ steps.verify-changes.outputs.has_substantial_changes }}
      release_notes: ${{ steps.verify-changes.outputs.release_notes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 2.x
      - name: Verify Changes
        id: verify-changes
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          ./scripts/check-changes
          echo "GitHub output file contents:"
          cat $GITHUB_OUTPUT