name: Check Changes

on:
  workflow_call:  # Makes this workflow reusable
    outputs:
      has_changes:
        description: "Whether substantial changes were found"
        value: ${{ jobs.check.outputs.has_changes }}
      release_notes:
        description: "Release notes if changes were found"
        value: ${{ jobs.check.outputs.release_notes }}
    secrets:
      ANTHROPIC_API_KEY:
        description: "Anthropic API key for generating release notes"
        required: true

jobs:
  check:
    runs-on: ubuntu-24.04  # Explicitly use the upcoming version
    outputs:
      has_changes: ${{ steps.check.outputs.has_changes }}
      release_notes: ${{ steps.check.outputs.release_notes }}
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - id: setup-deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - id: check
        run: |
          if ./.github/workflows/scripts/check-changes; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "release_notes<<EOF" >> $GITHUB_OUTPUT
            ./.github/workflows/scripts/check-changes --notes >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "release_notes=No substantial changes" >> $GITHUB_OUTPUT
          fi 