name: Linux Build & Test

on:
  workflow_call:  # Makes this workflow reusable 

jobs:
  linux:
    name: 🐧 Linux
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./...
        env:
          CGO_ENABLED: "1"  # Enable CGO for native builds

      - name: Test
        run: go test -v ./...
        env:
          GO_TEST_STREAM_OUTPUT: "1" 