name: Tests

on:
 workflow_call:  # Makes this workflow reusable 

jobs:
 test:
   timeout-minutes: 5  # Add timeout of 5 minutes
   strategy:
     matrix:
       os: [ubuntu-latest, windows-latest]
   runs-on: ${{ matrix.os }}
   steps:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0  # Fetch all history and tags

     - uses: actions/setup-go@v4
       with:
         go-version: '1.21'
         cache: false  # Disable built-in cache to use our own

     - uses: actions/cache@v4
       with:
         path: |
           ~/.cache/go-build
           ~/go/pkg/mod
         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
         restore-keys: |
           ${{ runner.os }}-go-
         restore-flags: '--exclude "**.go" --exclude "SECURITY.md" --exclude "LICENSE"'

     - run: go mod download
     - run: go test -v ./...