name: Tests

on:
  workflow_call:  # Makes this workflow reusable
  push:
    branches-ignore:
      - main     # Don't run on main since main.yml handles it
  pull_request:  # Run on PRs targeting any branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Generate SSH Key
        run: ssh-keygen -t rsa -f host.key -N ""

      - name: Get dependencies
        run: go get -v ./...

      - name: Run tests
        run: go test -v ./... 