on:
  workflow_call:  # Makes this workflow reusable

jobs:
  test:
    runs-on: ubuntu-24.04  # Explicitly use the upcoming version
    timeout-minutes: 5
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - id: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - id: cache-apt
        uses: actions/cache@v3
        with:
          path: |
            /var/lib/apt/lists
            /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/test-linux.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - id: install-deps
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh

      - id: go-test
        run: go test -v ./...
        env:
          CGO_ENABLED: "1"  # Enable CGO for native builds 